version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=meow
      - POSTGRES_PASSWORD=meowpass
      - POSTGRES_DB=meowhub
