
### Find All Users
GET http://localhost:3000/user/findAll


### Find User By Id
GET http://localhost:3000/user/findById/a8dd04bc-42d4-43a0-91cd-d6903b129532


### Create User
POST http://localhost:3000/user/create 
Content-Type: application/json 
{
  "name": "John Doe",
  "email": "johndoe@email.com",
  "password": "123456"
}


### Update User
POST http://localhost:3000/user/update
Content-Type: application/json
{
  "id": "a8dd04bc-42d4-43a0-91cd-d6903b129532",
  "name": "John Doe",
  "email": "new@email.com"
}


### Delete User
DELETE  http://localhost:3000/user/delete/d860ac78-30a1-417f-aa11-0db0195461a6

